on:
  push:
    branches: [ cloudsmith ]

env:
  REGISTRY: docker.cloudsmith.io

jobs:
  build-and-push-image:
    environment: cloudsmith
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    name: Upload to registry
    steps:
      - name: Checkout
        # uses: actions/checkout@v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: login to registry
        # uses: docker/login-action@v3.1.0
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.CLOUDSMITH_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # uses: docker/metadata-action@v5.5.1
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}
      - name: Build and push Docker image
        # uses: docker/build-push-action@v5.3.0
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
